### PR TITLE
Added set/get node instance parameter under Run.

### PR DESCRIPTION
**Pull request by konstan**
Connects to #12

### CODE REVIEW

**Comment by schaubl** [comment]
Do we want to expose the way to set a runtimeparameter ?
Currently I don't see any use case where this is useful (except to "hack" the Run).

@slipstream/crew @slipstream/owners : What do you think ?

**Comment by konstan** [comment]
IMO, it's OK to expose `set` operation, because it's part of an open API and it may help in integration with third-party services (we've seen this already with Interoot (Puppet) and CERN (heart-beat from cron (no-need to install/setup SS client))). 
There is a ticket already (need to find it) to protect certain run(time)-parameter from being overridden by user.  The latter option can be extended to let user decide which node instance runtime parameters can be re-set and by "whom".

**Comment by mebster** [comment]
+1 to @konstan suggestion

**Comment by schaubl** [comment]
Oops, I thought that I had already merged this PR yesterday.

**Comment by schaubl** [comment]
Because this is part of the official documentation now, it can allow users to break a Run so the following task has become much more important:
slipstream/SlipStreamServer#256
So I promoted it into `Shortlisted for Sprint`.

**Pull request merged**
